plugins:
  auth0:
    auth0_domain: "dev-zln-9j9k.us.auth0.com"
    auth0_client_id: "aVSmGxwWl21uHzaRIpRFrALRcKLYI0Ro"
    auth0_client_secret: "KhXIlhUeagW6yk9wD96pLk9YYo_tcCxfBJQoDsV86DTb1-Z10jyUGBdNsKCWqQ8U"
    # auth0_domain: "dev-florin.eu.auth0.com"
    # auth0_client_id: "hVr921UprMUxV2m2yiniPxt0ysZUNoMg"
    # auth0_client_secret: "uUkIv5ABwZuJcvbOrIPJpLFGYiMdawT8Jf_vEYCGx90ZTcRbdw8M1MHtkJjgGurc"
  json:
    file: "/Users/oanatanasoiu/projects/output.json"
  aserto:
    tenant: "97a900f1-2291-11ec-bf6c-005152ce7c18"
    authorizer: "authorizer.eng.aserto.com:8443"
    api_key: "e5cd3abf971e08b4e6947dc3012df05ce0bfa957e8cebba4babaf7f2304bb967"
  okta:
    okta_domain: "dev-77113960.okta.com"
    okta_api_token: "00tPUNIJQln3uCPc_hgDKyzj8Xb1ipBq-l2CmwPdCJ"